### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by arpit9616**
## Changes:
- `lib/socks5.js` -> file names are case sensitive in linux
- `lib/socks5TCP.js` -> need to call function with added parenthesis
- `lib'socks5UDP.js` -> use assignment operator instead of comparison operator

### CODE REVIEW

**Review by TekMonksGitHub — COMMENTED** [review]
Please confirm an end to end test was done as there is a code fix ...

**Comment by arpit9616** [comment]
Tested end-to-end for TCP Client.
Will test for UDP too.

**Comment by TekMonksGitHub** [comment]
> Tested end-to-end for TCP Client.
> Will test for UDP too.

Yes UDP is extremely important. This is a UDP fix.

**Comment by arpit9616** [comment]
Started testing for UDP.

**Comment by arpit9616** [comment]
Server breaks on critical error when testing for UDP.
Will document the problem and open an issue against it.

Reverting code fixes in UDP so above changes can be merged.
Necessary for running sockem on Linux machines.

**Pull request merged**
