### PR TITLE
Update crypt.js

### PR DESCRIPTION
**Pull request by arpit9616**
## Changes:
- Minor updates to JSDoc comments
- Modifications to not use `eval` when executing directly

> Tested

### CODE REVIEW

**Comment by arpit9616** [comment]
Since `crypt.js` is a common module in most of our repos,
Suggesting that we move the above fixes to remove `eval` across the board.

**Comment by TekMonksGitHub** [comment]
Agree. We gotta figure this out better btw - is there a way to symlink across repost in Git (think not). Failing this we should move such modules into its on Git repo and require extracting that repo on top (I know NPM is better, but we won't be publishing these as public NPMs). Maybe there is another  option?

**Comment by arpit9616** [comment]
Okay, I'll move this to other repos via PRs for now.
<br/>
For linking across repos, another option would be to: 
1. Add all common modules to a separate repo 
2. Add install scripts to our repos that use these modules (if they don't already have them) 
3. Download all required modules using the curl command to the required places from the common repo

> open for discussion

**Comment by TekMonksGitHub** [comment]
Yes I was thinking the same for now - common git repo and pull it via an install script.

It also then allows someone to have ownership and maintain the common code - e.g. if they is a cyrpt issue - assign to that repo and track it that way.

**Pull request merged**
